In [100]:
import pandas as pd

In [101]:
df = pd.read_csv("train.csv")

In [102]:
df['Age']=df['Age'].fillna(df['Age'].mean())

In [103]:
encoded_df = pd.get_dummies(df, columns=['Embarked'])

In [104]:
true_map={True:1,False:0}

In [105]:
encoded_df['Embarked_C']=encoded_df['Embarked_C'].map(true_map)

In [106]:
encoded_df['Embarked_S']=encoded_df['Embarked_S'].map(true_map)

In [107]:
encoded_df['Embarked_Q']=encoded_df['Embarked_Q'].map(true_map)

In [108]:
df = encoded_df

In [109]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex        Age  \
0                              Braund, Mr. Owen Harris    male  22.000000   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.000000   
2                               Heikkinen, Miss. Laina  female  26.000000   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.000000   
4                             Allen, Mr. William Henry    male  35.000000   
..                                                 ...     ...        ...   
886                              Montvila, Rev. Juozas    male  27.000000   
887                       Graham, Miss. Margaret Edith  female  19.000000   
888           Johnston, Miss. Catherine Helen "Carrie"  female  29.699118   
889                              Behr, Mr. Karl Howell    male  26.000000   
890                                Dooley, Mr. Patrick    male  32.000000   

     SibSp  Parch            Ticket     Fare Cabin  Embarked_C  Embarked_Q  \
0        1      0         A/5 21171   7.2500   NaN           0           0   
1        1      0          PC 17599  71.2833   C85           1           0   
2        0      0  STON/O2. 3101282   7.9250   NaN           0           0   
3        1      0            113803  53.1000  C123           0           0   
4        0      0            373450   8.0500   NaN           0           0   
..     ...    ...               ...      ...   ...         ...         ...   
886      0      0            211536  13.0000   NaN           0           0   
887      0      0            112053  30.0000   B42           0           0   
888      1      2        W./C. 6607  23.4500   NaN           0           0   
889      0      0            111369  30.0000  C148           1           0   
890      0      0            370376   7.7500   NaN           0           1   

     Embarked_S  
0             1  
1             0  
2             1  
3             1  
4             1  
..          ...  
886           1  
887           1  
888           1  
889           0  
890           0  

[891 rows x 14 columns]

In [110]:
gender_map={'male':0,'female':1}

In [111]:
df['Sex']=df['Sex'].map(gender_map)

In [112]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name  Sex        Age  SibSp  \
0                              Braund, Mr. Owen Harris    0  22.000000      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.000000      1   
2                               Heikkinen, Miss. Laina    1  26.000000      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.000000      1   
4                             Allen, Mr. William Henry    0  35.000000      0   
..                                                 ...  ...        ...    ...   
886                              Montvila, Rev. Juozas    0  27.000000      0   
887                       Graham, Miss. Margaret Edith    1  19.000000      0   
888           Johnston, Miss. Catherine Helen "Carrie"    1  29.699118      1   
889                              Behr, Mr. Karl Howell    0  26.000000      0   
890                                Dooley, Mr. Patrick    0  32.000000      0   

     Parch            Ticket     Fare Cabin  Embarked_C  Embarked_Q  \
0        0         A/5 21171   7.2500   NaN           0           0   
1        0          PC 17599  71.2833   C85           1           0   
2        0  STON/O2. 3101282   7.9250   NaN           0           0   
3        0            113803  53.1000  C123           0           0   
4        0            373450   8.0500   NaN           0           0   
..     ...               ...      ...   ...         ...         ...   
886      0            211536  13.0000   NaN           0           0   
887      0            112053  30.0000   B42           0           0   
888      2        W./C. 6607  23.4500   NaN           0           0   
889      0            111369  30.0000  C148           1           0   
890      0            370376   7.7500   NaN           0           1   

     Embarked_S  
0             1  
1             0  
2             1  
3             1  
4             1  
..          ...  
886           1  
887           1  
888           1  
889           0  
890           0  

[891 rows x 14 columns]

In [113]:
X = df[['Pclass', 'Sex','Age','SibSp','Fare','Embarked_C','Embarked_Q','Embarked_S']]
y = df['Survived']

In [114]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split (X, y, test_size=0.2, random_state=0)
print('Total no. of samples: Training and Testing dataset separately!')

Total no. of samples: Training and Testing dataset separately!


In [115]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [116]:
import tensorflow as tf

X_train = tf.constant(X_train)
y_train = tf.constant(y_train)
X_test = tf.constant(X_test)
y_test = tf.constant(y_test)

In [117]:
import keras 

In [118]:
# Create the model
model = tf.keras.Sequential([
                  tf.keras.layers.Dense(128, activation="relu"),
                  tf.keras.layers.Dense(256, activation="relu"),
                  tf.keras.layers.Dense(128, activation="relu"),
                  tf.keras.layers.Dense(1, activation="sigmoid")
 ])
# Compile the model
model.compile(loss="binary_crossentropy",
              optimizer="Adam",
              metrics=["accuracy"])



In [119]:
# Fit the model
history = model.fit(X_train,
                    y_train,
                    epochs=50,
                    validation_data=(X_test, y_test),
                    verbose=0)
model.evaluate(X_test, y_test)


6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8073 - loss: 0.3926 


[0.41341957449913025, 0.7988826632499695]

In [120]:
y_pred_prob = model.predict(X_test)

# Convert probabilities to binary values (0 or 1)
y_pred = (y_pred_prob > 0.5).astype("int32")

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step


In [121]:
y_pred

array([[0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
    

In [122]:
from sklearn import metrics 

In [123]:
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
print('Confusion matrix')
print(cnf_matrix)
print('---------------')
print('Precision:', metrics.precision_score(y_test, y_pred))
print('Recall:', metrics.recall_score(y_test, y_pred))
print('F1 Score:', metrics.f1_score(y_test, y_pred))
print('Accuracy Score:', metrics.accuracy_score(y_test, y_pred))

Confusion matrix
[[95 15]
 [21 48]]
---------------
Precision: 0.7619047619047619
Recall: 0.6956521739130435
F1 Score: 0.7272727272727273
Accuracy Score: 0.7988826815642458


In [124]:
df = pd.read_csv("test.csv")

In [125]:
df['Fare']=df['Fare'].fillna(df['Fare'].median())

In [126]:
df['Age']=df['Age'].fillna(df['Age'].mean())

In [127]:
gender_map={'male':0,'female':1}

In [128]:
df['Sex']=df['Sex'].map(gender_map)

In [129]:
df = pd.get_dummies(df, columns=['Embarked'])

In [130]:
true_map={True:1,False:0}

In [131]:
df['Embarked_Q']=df['Embarked_Q'].map(true_map)

In [132]:
df['Embarked_S']=df['Embarked_S'].map(true_map)

In [133]:
df['Embarked_C']=df['Embarked_C'].map(true_map)

In [134]:
df

PassengerId  Pclass                                          Name  Sex  \
0            892       3                              Kelly, Mr. James    0   
1            893       3              Wilkes, Mrs. James (Ellen Needs)    1   
2            894       2                     Myles, Mr. Thomas Francis    0   
3            895       3                              Wirz, Mr. Albert    0   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)    1   
..           ...     ...                                           ...  ...   
413         1305       3                            Spector, Mr. Woolf    0   
414         1306       1                  Oliva y Ocana, Dona. Fermina    1   
415         1307       3                  Saether, Mr. Simon Sivertsen    0   
416         1308       3                           Ware, Mr. Frederick    0   
417         1309       3                      Peter, Master. Michael J    0   

          Age  SibSp  Parch              Ticket      Fare Cabin  Embarked_C  \
0    34.50000      0      0              330911    7.8292   NaN           0   
1    47.00000      1      0              363272    7.0000   NaN           0   
2    62.00000      0      0              240276    9.6875   NaN           0   
3    27.00000      0      0              315154    8.6625   NaN           0   
4    22.00000      1      1             3101298   12.2875   NaN           0   
..        ...    ...    ...                 ...       ...   ...         ...   
413  30.27259      0      0           A.5. 3236    8.0500   NaN           0   
414  39.00000      0      0            PC 17758  108.9000  C105           1   
415  38.50000      0      0  SOTON/O.Q. 3101262    7.2500   NaN           0   
416  30.27259      0      0              359309    8.0500   NaN           0   
417  30.27259      1      1                2668   22.3583   NaN           1   

     Embarked_Q  Embarked_S  
0             1           0  
1             0           1  
2             1           0  
3             0           1  
4             0           1  
..          ...         ...  
413           0           1  
414           0           0  
415           0           1  
416           0           1  
417           0           0  

[418 rows x 13 columns]

In [135]:
X = df[['Pclass', 'Sex','Age','SibSp','Fare','Embarked_C','Embarked_Q','Embarked_S']]

In [42]:
# from sklearn.preprocessing import StandardScaler
# sc = StandardScaler()
# sc.fit(X)
# X_test = sc.transform(X)

In [136]:
y_pred_prob = model.predict(X)

# Convert probabilities to binary values (0 or 1)
y_pred = (y_pred_prob > 0.5).astype("int32")

14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step 


In [137]:
y_pred

array([[0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
    

In [138]:
X=pd.DataFrame(y_pred, columns=['Survived'])

In [140]:
Y=df[['PassengerId']]

In [141]:
X

Survived
0           0
1           0
2           0
3           0
4           1
..        ...
413         0
414         1
415         0
416         0
417         0

[418 rows x 1 columns]

In [142]:
result = pd.concat([Y, X], axis=1)

In [143]:
result.to_csv('output5.csv', index=False)